CREATE TABLE T_JOGO (
    ID_JOGO NUMBER PRIMARY KEY,
    DS_NOME VARCHAR2(100) NOT NULL,
    DT_LANCAMENTO DATE,
    DS_CLASSIFICACAO VARCHAR2(20)
);

CREATE SEQUENCE SQ_T_JOGO
START WITH 1
INCREMENT BY 1
NOCACHE;

ALTER TABLE T_JOGO ADD ID_DESENVOLVEDORA NUMBER;
ALTER TABLE T_JOGO ADD CONSTRAINT FK_DESENVOLVEDORA FOREIGN KEY (ID_DESENVOLVEDORA) REFERENCES T_DESENVOLVEDORA(ID_DESENVOLVEDORA);


CREATE TABLE T_DESENVOLVEDORA (
    ID_DESENVOLVEDORA NUMBER PRIMARY KEY,
    NM_DESENVOLVEDORA VARCHAR2(100) NOT NULL
);

DROP TABLE T_DESENVOLVEDORA;

CREATE SEQUENCE SQ_T_DESENVOLVEDORA
START WITH 1
INCREMENT BY 1
NOCACHE;