CREATE TABLE T_JOGO (
    ID_JOGO NUMBER PRIMARY KEY,
    DS_NOME VARCHAR2(100) NOT NULL,
    DT_LANCAMENTO DATE,
    DS_CLASSIFICACAO VARCHAR2(20)
);

CREATE SEQUENCE SQ_T_JOGO
START WITH 1
INCREMENT BY 1
NOCACHE;